name: ping_watcher_android
description: Visual DNS and internet quality monitor for Android.
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  fl_chart: ^0.68.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
